const char *home_html = 
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"    <style>\n"
"        body {\n"
"            font-family: 'Roboto', sans-serif;\n"
"            background-color: #f4f4f4;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            text-align: center;\n"
"            display: flex;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            height: 100vh;\n"
"        }\n"
"        h1 {\n"
"            color: #333;\n"
"            font-size: 2.5rem;\n"
"            margin-bottom: 30px;\n"
"        }\n"
"        ul {\n"
"            list-style: none;\n"
"            padding: 0;\n"
"            margin: 0;\n"
"        }\n"
"        li {\n"
"            margin: 15px 0;\n"
"        }\n"
"        button {\n"
"            background-color: #4CAF50;\n"
"            color: white;\n"
"            padding: 12px 30px;\n"
"            text-decoration: none;\n"
"            font-size: 18px;\n"
"            border-radius: 5px;\n"
"            border: none;\n"
"            cursor: pointer;\n"
"            transition: background-color 0.3s ease;\n"
"        }\n"
"        button:hover {\n"
"            background-color: #45a049;\n"
"        }\n"
"        .container {\n"
"            text-align: left;\n"
"            max-width: 500px;\n"
"            width: 100%;\n"
"            padding: 20px;\n"
"            background-color: #ffffff;\n"
"            box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);\n"
"            border-radius: 8px;\n"
"        }\n"
"        .footer {\n"
"            font-size: 0.9rem;\n"
"            color: #7a7a7a;\n"
"            position: fixed;\n"
"            bottom: 10px;\n"
"            width: 100%;\n"
"            text-align: center;\n"
"        }\n"
"    </style>\n"
"    <title>Home</title>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>Welcome to the ESP32S3 Smart Home Screen</h1>\n"
"        <ul>\n"
"            <li><a href=\"/get_temp\"><button>Get Chip Temp</button></a></li>\n"
"            <li><a href=\"/get_led_state\"><button>Get LED State</button></a></li>\n"
"            <li><a href=\"/ledon\"><button>Turn LED ON</button></a></li>\n"
"            <li><a href=\"/ledoff\"><button>Turn LED OFF</button></a></li>\n"
"        </ul>\n"
"    </div>\n"
"    <div class=\"footer\">ESP32S3 Powered Smart Home Web Server</div>\n"
"</body>\n"
"</html>";

const char *ledon_html =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"    <style>\n"
"        body {\n"
"            font-family: 'Roboto', sans-serif;\n"
"            background-color: #f4f4f4;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            text-align: center;\n"
"            display: flex;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            height: 100vh;\n"
"        }\n"
"        h1 {\n"
"            color: #333;\n"
"            font-size: 2.5rem;\n"
"            margin-bottom: 30px;\n"
"        }\n"
"        p {\n"
"            font-size: 1.2rem;\n"
"            color: #4CAF50;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        button {\n"
"            background-color: #4CAF50;\n"
"            color: white;\n"
"            padding: 12px 30px;\n"
"            text-decoration: none;\n"
"            font-size: 18px;\n"
"            border-radius: 5px;\n"
"            border: none;\n"
"            cursor: pointer;\n"
"            transition: background-color 0.3s ease;\n"
"        }\n"
"        button:hover {\n"
"            background-color: #45a049;\n"
"        }\n"
"    </style>\n"
"    <title>LED On</title>\n"
"</head>\n"
"<body>"
"    <div class=\"container\">"
"        <h1>LED is Now ON</h1>\n"
"        <p>The LED on your ESP32S3 is currently turned on.</p>\n"
"        <a href=\"/ledoff\"><button>Turn LED OFF</button></a>\n"
"        <br><br>\n"
"        <p><a href=\"/\">Back to Home</a></p>"
"    </div>"
"</body>"

#if 0
"<body>\n"
"    <div>\n"
"        <h1>LED is Now ON</h1>\n"
"        <p>The LED on your ESP32S3 is currently turned on.</p>\n"
"        <a href=\"/ledoff\"><button>Turn LED OFF</button></a>\n"
"        <br><br>\n"
"        <a href=\"/\"><button>Go Back to Home</button></a>\n"
"    </div>\n"
"</body>\n"
#endif
"</html>";

const char *ledoff_html =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"    <style>\n"
"        body {\n"
"            font-family: 'Roboto', sans-serif;\n"
"            background-color: #f4f4f4;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            text-align: center;\n"
"            display: flex;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            height: 100vh;\n"
"        }\n"
"        h1 {\n"
"            color: #333;\n"
"            font-size: 2.5rem;\n"
"            margin-bottom: 30px;\n"
"        }\n"
"        p {\n"
"            font-size: 1.2rem;\n"
"            color: #f44336;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        button {\n"
"            background-color: #f44336;\n"
"            color: white;\n"
"            padding: 12px 30px;\n"
"            text-decoration: none;\n"
"            font-size: 18px;\n"
"            border-radius: 5px;\n"
"            border: none;\n"
"            cursor: pointer;\n"
"            transition: background-color 0.3s ease;\n"
"        }\n"
"        button:hover {\n"
"            background-color: #e53935;\n"
"        }\n"
"    </style>\n"
"    <title>LED Off</title>\n"
"</head>\n"

"<body>"
"    <div class=\"container\">"
"        <h1>LED is Now OFF</h1>\n"
"        <p>The LED on your ESP32S3 is currently turned off.</p>\n"
"        <a href=\"/ledon\"><button>Turn LED ON</button></a>\n"
"        <br><br>\n"
"        <p><a href=\"/\">Back to Home</a></p>"
"    </div>"
"</body>"

#if 0
"<body>\n"
"    <div>\n"
"        <h1>LED is Now OFF</h1>\n"
"        <p>The LED on your ESP32S3 is currently turned off.</p>\n"
"        <a href=\"/ledon\"><button>Turn LED ON</button></a>\n"
"        <br><br>\n"
"        <a href=\"/\"><button>Go Back to Home</button></a>\n"
"    </div>\n"
"</body>\n"
#endif
"</html>";

const char *temp_html_body = 
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"    <meta charset=\"UTF-8\">"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"    <title>Temperature Information</title>"
"    <style>"
"        body {"
"            font-family: Arial, sans-serif;"
"            background-color: #f0f4f8;"
"            margin: 0;"
"            padding: 0;"
"            display: flex;"
"            justify-content: center;"
"            align-items: center;"
"            height: 100vh;"
"        }"
"        .container {"
"            background-color: #fff;"
"            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);"
"            padding: 30px;"
"            border-radius: 8px;"
"            text-align: center;"
"            width: 100%;"
"            max-width: 600px;"
"        }"
"        h1 {"
"            color: #333;"
"            font-size: 2rem;"
"            margin-bottom: 20px;"
"        }"
"        p {"
"            color: #666;"
"            font-size: 1.1rem;"
"        }"
"        a {"
"            color: #4CAF50;"
"            text-decoration: none;"
"            font-weight: bold;"
"        }"
"        a:hover {"
"            text-decoration: underline;"
"        }"
"    </style>"
"</head>"
"<body>"
"    <div class=\"container\">"
"        <h1>Current Chip Temperature: %.2f°C</h1>"
"        <p>Temperature data for your device is shown above. "
"        <p><a href=\"/\">Back to Home</a></p>"
"    </div>"
"</body>"
"</html>";

const char *led_state_html_body = 
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"    <meta charset=\"UTF-8\">"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
"    <title>LED State</title>"
"    <style>"
"        body {"
"            font-family: Arial, sans-serif;"
"            background-color: #f0f4f8;"
"            margin: 0;"
"            padding: 0;"
"            display: flex;"
"            justify-content: center;"
"            align-items: center;"
"            height: 100vh;"
"        }"
"        .container {"
"            background-color: #fff;"
"            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);"
"            padding: 30px;"
"            border-radius: 8px;"
"            text-align: center;"
"            width: 100%;"
"            max-width: 600px;"
"        }"
"        h1 {"
"            color: #333;"
"            font-size: 2rem;"
"            margin-bottom: 20px;"
"        }"
"        p {"
"            color: #666;"
"            font-size: 1.1rem;"
"        }"
"        a {"
"            color: #4CAF50;"
"            text-decoration: none;"
"            font-weight: bold;"
"        }"
"        a:hover {"
"            text-decoration: underline;"
"        }"
"    </style>"
"</head>"
"<body>"
"    <div class=\"container\">"
"        <h1>LED State: %s</h1>"
"        <p><a href=\"/\">Back to Home</a></p>"
"    </div>"
"</body>"
"</html>";

char temp_html[2048];